### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by fipoucat** [ca-vi/Climatology_Package#4]
Trying to install using install_github but still having error, need help fix it on osx.Error: package ‘XLConnectJars’ could not be loaded
Execution halted
ERROR: lazy loading failed for package ‘FGClimatology’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/FGClimatology’
Error: Failed to install 'FGClimatology' from GitHub:
  (converted from warning) installation of package ‘/var/folders/wb/pry3ghxn4s30_yrgyynbrxs80000gn/T//RtmpPilXaC/file15e1b219cf344/FGClimatology_0.9.2.tar.gz’ had non-zero exit status

**Comment by fipoucat** [comment]
same problem both mac and window

**Comment by fipoucat** [comment]
looks package no longer maintained?

**Comment by ca-vi** [comment]
@fipoucat this package is no longer updated. It was used for teaching and research at [Chair of Climatology TU Berlin](https://www.klima.tu-berlin.de/index.php?show=home_start&lan=en)

If you want to calculate MRT, UCTI or PMV use the scripts available here on GitHub or contact [Alex Krug](https://www.klima.tu-berlin.de/index.php?show=team_krug&lan=en) (a.krug@tu-berlin.de)
